<template>
  <div class="page">
    <LandingNav />

    <div class="page-hero">
      <div class="page-eyebrow">
        <div class="eyebrow-line" aria-hidden="true"></div>
        <span>LEGAL</span>
        <div class="eyebrow-line" aria-hidden="true"></div>
      </div>
      <h1 class="page-title">Privacy <span class="gold">Policy</span></h1>
      <p class="page-sub">Last updated: January 1, {{ year }}</p>
    </div>

    <div class="page-content">
      <div class="legal-body">
        <section class="legal-section" v-for="section in sections" :key="section.title">
          <h2 class="legal-heading">{{ section.title }}</h2>
          <p class="legal-text" v-for="para in section.paragraphs" :key="para">{{ para }}</p>
        </section>
      </div>
    </div>

    <LandingFooter />
  </div>
</template>

<script setup lang="ts">
import LandingNav from '@/components/landing/LandingNav.vue'
import LandingFooter from '@/components/landing/LandingFooter.vue'

const year = new Date().getFullYear()

const sections = [
  {
    title: '1. Information We Collect',
    paragraphs: [
      'We collect information you provide when creating an account (name, email address), information generated by your use of the Service (monitoring configurations, check results, incident data, and usage metrics), and technical information from your browser or device (IP address, user agent, cookies).',
      'We do not collect the content of the services you monitor — only availability and response-time metadata.',
    ],
  },
  {
    title: '2. How We Use Your Information',
    paragraphs: [
      'We use your information to provide and improve the Service, send you monitoring alerts and notifications you configure, communicate with you about your account and our Service, and comply with legal obligations.',
      'We do not sell your personal data to third parties. We do not use your data to train AI models.',
    ],
  },
  {
    title: '3. Data Retention',
    paragraphs: [
      'We retain monitoring data for the period specified by your plan (30 days for Starter, 12 months for Professional, unlimited for Enterprise). Account data is retained for as long as your account is active and for 30 days after deletion to allow recovery.',
    ],
  },
  {
    title: '4. Data Security',
    paragraphs: [
      'All data is encrypted in transit using TLS 1.3 and at rest using AES-256. Our infrastructure runs on SOC 2 Type II certified cloud providers. We implement access controls, audit logging, and regular security reviews.',
      'No method of electronic transmission or storage is 100% secure. We cannot guarantee absolute security, but we take commercially reasonable measures to protect your information.',
    ],
  },
  {
    title: '5. Cookies',
    paragraphs: [
      'We use session cookies to keep you logged in and preference cookies to remember your settings. We do not use third-party tracking or advertising cookies.',
      'You can disable cookies in your browser settings, but some features of the Service may not function correctly without them.',
    ],
  },
  {
    title: '6. Third-Party Services',
    paragraphs: [
      'We use a limited number of third-party services to operate the platform (cloud hosting, transactional email). These providers are contractually bound to process your data only as instructed and in compliance with applicable privacy laws.',
    ],
  },
  {
    title: '7. Your Rights',
    paragraphs: [
      'Depending on your location, you may have rights to access, correct, delete, or export your personal data. To exercise these rights, contact us at privacy@cloudpulse.io. We will respond within 30 days.',
    ],
  },
  {
    title: '8. Contact',
    paragraphs: [
      'For privacy-related questions, contact our Data Protection team at privacy@cloudpulse.io or visit our Contact page.',
    ],
  },
]
</script>

<style scoped>
.page {
  background: #0A0A0A;
  color: #F2F0E4;
  min-height: 100vh;
  font-family: 'Josefin Sans', 'Inter', sans-serif;
}

.page-hero {
  text-align: center;
  padding: 140px 32px 80px;
  border-bottom: 1px solid rgba(212,175,55,0.1);
}
.page-eyebrow {
  display: flex;
  align-items: center;
  gap: 16px;
  justify-content: center;
  margin-bottom: 24px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.25em;
  color: #D4AF37;
}
.eyebrow-line {
  width: 40px;
  height: 1px;
  background: rgba(212,175,55,0.4);
}
.page-title {
  font-family: 'Marcellus', Georgia, serif;
  font-size: clamp(36px, 6vw, 64px);
  font-weight: 400;
  letter-spacing: 0.08em;
  color: #F2F0E4;
  margin-bottom: 16px;
}
.gold { color: #D4AF37; }
.page-sub {
  font-size: 13px;
  color: #555;
  font-weight: 300;
  letter-spacing: 0.06em;
}

.page-content {
  max-width: 760px;
  margin: 0 auto;
  padding: 80px 32px;
}

.legal-body {
  display: flex;
  flex-direction: column;
  gap: 40px;
}

.legal-section { display: flex; flex-direction: column; gap: 12px; }

.legal-heading {
  font-family: 'Marcellus', Georgia, serif;
  font-size: 16px;
  letter-spacing: 0.1em;
  color: #D4AF37;
  padding-bottom: 10px;
  border-bottom: 1px solid rgba(212,175,55,0.15);
}

.legal-text {
  font-size: 16px;
  color: #777;
  line-height: 1.85;
  font-weight: 300;
}

@media (max-width: 600px) {
  .page-content { padding: 48px 20px; }
  .page-hero { padding: 120px 20px 60px; }
}
</style>
